### ISSUE TITLE
Doesn't work when more than one space in a name

### ISSUE THREAD

**Issue by saewitz** [MatthewFoulk/UMDProfessorRatings#1]
Hi, cool extension!

Just a note, it doesn't work when a professor has more than one space in their name. This is because of how the extension handles names on Testudo. Here are the relevant lines: https://github.com/MatthewFoulk/UMDProfessorRatings/blob/master/content.js#L60-L63

**Comment by MatthewFoulk** [comment]
Thanks for the feedback! I've added some minor changes to handle multi-spaced names. Once the updated version is approved by the Chrome Web Store, it should be good to go.
